travis:
  secure:
    BINSTAR_TOKEN: YYm9oIVRLAZjOY5YSh2UFsWlQvvG5CQeCJ2Gr8owE/muIUdP4SPNNuv8dSgqU70mOM2Ue4MC6AWbw7w5wpG6Gn7cDCOYLhpMne38/T3bdFQHX6GrBxyv0JICzUQro+8yHrvX2vOOLeS/6pe0L3t4DGLRbJw519lKhJqnqJzTS8P4CdGgnhJ6iSiemDj+wws6lW5x/T8kmyEdmFdFFs3pKb2j0kIKdj/ew6CB3reiDjFHdB6vKaBnzo2ODa4kcxsTQeqCyVTVBlJ4jHMMKdBWFaPSpd5zqxyA2fuopDGUyfRmmexh0asTNQQeJk9TwDdbalogdWTj2Zc+hyKkDjATzfSRguptsdIndrLoDZUOmQmQhMeWDgAKdWqLhM/YE8prV+I+1Vc7XNcgu+MwiI2fTQQQQul3Nid4IIb7420QZ4wmSmhSoVpkRWj3GPAFEs5ucT/KH4ZVAO44JZFotLaZCYj0Tdy6j/InfQBhr3Kub0hrMBI+vmZGVVHGSEYPlJT+ty29sHF6HkfNTfNxnywiOwS2cyY7BG9q3cihU9QKUF3iTPOSe8s7MytGRKbpWn78w7l+Hk1760VBcoWIFOuUPq5tm0UZmD8FyM01zKN9DXNO5PB3KEHuRzkiAsSYr4SXFX+D+0FIw79bg8777AV9Qdi5/gJK6TzgA2oxDkED6OM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
